"use client";

import { Brain, ShieldCheck, Sparkles, Zap } from "lucide-react";
import Link from "next/link";
import type { ReactNode } from "react";

type Props = {
  title: string;
  subtitle?: string;
  children: ReactNode;
  footer?: ReactNode;
};

export function AuthShell({ title, subtitle, children, footer }: Props) {
  return (
    <div className="relative min-h-screen w-full overflow-hidden bg-aurora">
      {/* decorative orbs */}
      <div className="pointer-events-none absolute -left-32 top-20 h-72 w-72 animate-floaty rounded-full bg-atom-accent/25 blur-3xl" />
      <div className="pointer-events-none absolute -right-24 bottom-10 h-72 w-72 animate-floaty rounded-full bg-cyan-400/20 blur-3xl [animation-delay:1.5s]" />
      <div className="absolute inset-0 bg-grid-dense opacity-[0.35]" />

      <div className="relative mx-auto grid min-h-screen max-w-7xl grid-cols-1 lg:grid-cols-[1.05fr_1fr]">
        {/* ---- left: brand / pitch ---- */}
        <aside className="hidden flex-col justify-between p-12 lg:flex">
          <Link href="/" className="inline-flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-atom-accent to-cyan-500 text-atom-deep shadow-glow">
              <Brain className="h-5 w-5" />
            </div>
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-atom-accent">AtomAdapt</p>
              <p className="text-sm text-atom-muted">Smart Adaptive LMS · for atomcamp</p>
            </div>
          </Link>

          <div className="max-w-md space-y-6">
            <div className="inline-flex items-center gap-2 rounded-full border border-atom-accent/25 bg-atom-panel/60 px-3 py-1 text-xs font-medium text-atom-accent">
              <Sparkles className="h-3 w-3" />
              Inter-University National AI Hackathon
            </div>
            <h2 className="text-4xl font-bold leading-tight tracking-tight text-balance">
              Personalized paths.{" "}
              <span className="text-shimmer">Real-time insight.</span>
            </h2>
            <p className="text-atom-muted text-base leading-relaxed">
              Every learner gets a living profile &mdash; goals, struggles, confidence &mdash; that drives
              recommendations, AI tutoring, and instructor signals.
            </p>

            <div className="grid gap-3">
              <Feature icon={<Sparkles className="h-4 w-4" />} title="AI onboarding diagnostic">
                Goal-aware quizzes generated by an LLM build your Learner DNA in minutes.
              </Feature>
              <Feature icon={<Zap className="h-4 w-4" />} title="Semantic recommendations">
                Embeddings + cosine match courses to the human behind the email — not a tag.
              </Feature>
              <Feature icon={<ShieldCheck className="h-4 w-4" />} title="Instructor intelligence">
                Trained risk scores flag who&apos;s struggling and draft outreach in one click.
              </Feature>
            </div>
          </div>

          <p className="text-xs text-atom-muted/80">
            © {new Date().getFullYear()} AtomAdapt · Built for the National AI Hackathon
          </p>
        </aside>

        {/* ---- right: form card ---- */}
        <main className="flex items-center justify-center p-6 sm:p-10">
          <div className="w-full max-w-md">
            <Link href="/" className="mb-8 flex items-center gap-3 lg:hidden">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-atom-accent to-cyan-500 text-atom-deep shadow-glow">
                <Brain className="h-5 w-5" />
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-widest text-atom-accent">AtomAdapt</p>
                <p className="text-xs text-atom-muted">Smart Adaptive LMS</p>
              </div>
            </Link>

            <div className="glass rounded-3xl border border-atom-border/70 p-8 shadow-2xl">
              <div className="mb-6 space-y-1">
                <h1 className="text-2xl font-semibold text-atom-text">{title}</h1>
                {subtitle && <p className="text-sm text-atom-muted">{subtitle}</p>}
              </div>
              {children}
            </div>
            {footer && <p className="mt-6 text-center text-sm text-atom-muted">{footer}</p>}
          </div>
        </main>
      </div>
    </div>
  );
}

function Feature({ icon, title, children }: { icon: ReactNode; title: string; children: ReactNode }) {
  return (
    <div className="flex gap-3 rounded-2xl border border-atom-border/50 bg-atom-panel/50 p-4 backdrop-blur">
      <div className="flex h-9 w-9 flex-none items-center justify-center rounded-xl border border-atom-accent/30 bg-atom-accent/10 text-atom-accent">
        {icon}
      </div>
      <div>
        <p className="text-sm font-semibold text-atom-text">{title}</p>
        <p className="text-xs leading-relaxed text-atom-muted">{children}</p>
      </div>
    </div>
  );
}
